global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mikrotik'
    static_configs:
      - targets:
        - 10.1.1.2
    metrics_path: /snmp
    params:
      module: [mikrotik] # <--- Pastikan ini 'mikrotik'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116