services:

   # Kontainer pembantu untuk memperbaiki permission
  init-grafana:
    image: alpine:latest
    container_name: init-grafana
    user: root
    volumes:
      - ./grafana:/var/lib/grafana-fix
    command: chown -R 472:472 /var/lib/grafana-fix
    
  # 1. SNMP Exporter: Jembatan SNMP ke Prometheus
  snmp-exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp-exporter
    restart: always
    ports:
      - "9116:9116"  # <--- INI YANG HILANG
    volumes:
      - ./snmp/snmp.yml:/etc/snmp_exporter/snmp.yml

  # 2. Prometheus: Database Time-Series
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - snmp-exporter

  # 3. Grafana: Dashboard Visualisasi
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Password login pertama kali
    volumes:
      - ./grafana/grafana-data:/var/lib/grafana
